# -*- coding: utf-8 -*-
"""Windows system-tray icon.

When the server starts on Windows, ``start()`` creates a tray icon with a menu:

* **打开 WebUI / Open WebUI** — re-opens the app in the default browser.
* **退出 / Quit** — stops the tray icon and shuts the server down.

The icon is loaded from ``static/favicon.ico`` (generated by ``make_icon.py``).
pystray + Pillow are used (both are pure-Python-friendly on Windows). The icon
runs on a background thread; ``icon.run`` blocks until ``icon.stop`` is called,
which happens from the *Quit* menu item. Everything is wrapped so that, if the
tray cannot be created (no session, missing libs, non-Windows), the server just
keeps running normally.
"""

import os
import sys
import threading
import webbrowser

_STATIC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "static")
ICON_FILE = os.path.join(_STATIC_DIR, "favicon.ico")


def start(url, on_quit):
    """Create the tray icon. Returns the icon or ``None`` if unavailable.

    ``on_quit`` is called (from the tray thread) when the user picks *Quit*.
    """
    if sys.platform != "win32":
        return None
    try:
        import pystray
        from PIL import Image
    except Exception:
        return None

    image = Image.open(ICON_FILE)

    def open_webui(_icon, _item):
        threading.Thread(target=lambda: webbrowser.open(url), daemon=True).start()

    def quit_app(icon, _item):
        try:
            icon.stop()          # removes the tray icon, ends icon.run()
        except Exception:
            pass
        on_quit()                # shut the server down

    menu = pystray.Menu(
        pystray.MenuItem("打开 WebUI / Open WebUI", open_webui, default=True),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("退出 / Quit", quit_app),
    )
    icon = pystray.Icon("livecsv", image, f"LiveCSV\n{url}", menu)
    # icon.run blocks; run it on a daemon thread so it doesn't block Flask.
    threading.Thread(target=icon.run, daemon=True).start()
    return icon
